name: 'uncrustify-checker'
author: 'dst'
description: 'Checks if code is properly formatted using uncrustify'

branding:
    icon: 'type'
    color: 'purple'
runs:
    using: 'docker'
    image: 'Dockerfile'

inputs:
    configFile:
        description: 'Path to Uncrustify configuration file'
        default: '/uncrustify.cfg'
        required: false
    checkedPaths:
        description: 'Semicolon seperated paths which Uncrustify will check'
        default: ''
        required: false
