name: 'uncrustify-check'
author: 'mib <mib@mib.dev>'
description: 'Checks if code is properly formatted using uncrustify'

branding:
    icon: 'type'
    color: 'purple'
runs:
    using: 'docker'
    image: 'Dockerfile'

inputs:
    configFile:
        description: 'Path to Uncrustify configuration file'
        default: '/uncrustify-default.cfg'
        required: false
